apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-django-clearsessions
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/component: clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      template:
        metadata:
          labels:
            app.kubernetes.io/name: django-app
            app.kubernetes.io/component: clearsessions
        spec:
          containers:
          - name: clearsessions
            image: django-app
            imagePullPolicy: IfNotPresent
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - configMapRef:
                  name: test-django-config
          restartPolicy: Never