apiVersion: v1
kind: Service
metadata:
  name: test-django-service
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/component: test
spec:
  type: ClusterIP
  ports:
    - name: external-port
      port: 25257
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/component: test